### ISSUE TITLE
Wrong in `headers-list` when A+/B+

### ISSUE THREAD

**Issue by suapapa** [google/periph#139]
Run `headers-list` on my RPi B+ only returns 26 pins for P1.
revision check code in `host/rpi/rpi.go` treats all RPi v1 have same P1 header
But it's not.

Latest RPi v1 (which ends with `+`) has 40 pins header for P1
* 26 pins for P1 A, B
* 40 pins for P1, A+(rev. 0012) and B+(rev. 0010 and 0013)

**Comment by maruel** [comment]
See https://github.com/google/periph/pull/138
