### ISSUE TITLE
new: Support devices on the Enviro pHAT

### ISSUE THREAD

**Issue by maxekman** [google/periph#141]
The Enviro pHAT is an affordable set of sensors for environment sensing. This issue is a public todo for me when implementing the drivers for it

Devices on the HAT:
- [x]  BMP280, temperature/pressure sensor
- [ ]  TCS3472, light and RGB colour sensor
- [ ]  LSM303D, accelerometer/magnetometer sensor
- [x]  ADS1015, 4-channel 5v tolerant 12-bit ADC
- [ ]  Two GPIO controlled LEDs for illumination of the light sensor, not really a device

Manufacturer: https://shop.pimoroni.com/products/enviro-phat
Device info: https://pinout.xyz/pinout/enviro_phat

**Comment by maruel** [comment]
I found it on [Adafruit](https://www.adafruit.com/product/3194) but it's out of stock. Pimoroni has even more reasonable shipping rates to Canada than Adafruit so I may order from there.

For now add it to experimental/ and once you have a smoke test and good unit test coverage, we can move it back into the official tree.

**Comment by maruel** [comment]
I prefer per device smoketest, as it's more reusable.

**Comment by UnAfraid** [comment]
We may scratch BMP280 of the list since https://github.com/google/periph/commit/252733acf606c513fa14dcff77a61fe0051b67d6

**Comment by maxekman** [comment]
I'll leave it checked in the list as that device is still on the Enviro pHAT.

**Comment by bezineb5** [comment]
PR #304 implemented ADS1015, so you can check it.

**Comment by NeuralSpaz** [comment]
I have a discrete TCS3472 and am willing to contribute device driver.

**Comment by maruel** [comment]
Ported to https://github.com/periph/devices/issues/61.
