### ISSUE TITLE
ssd1306 wrong resolution on 128x32 OLED

### ISSUE THREAD

**Issue by mikegleasonjr** [google/periph#166]
Using this product on Raspberry Pi Zero W using latest stretch:

Adafruit PiOLED - 128x32 Monochrome OLED Add-on for Raspberry Pi
https://www.adafruit.com/product/3527

The image seems wrong using the `ssd1306` cmd provided in the package:

```
./ssd1306 -h 32
```

Results in:

![img_20171023_020257](https://user-images.githubusercontent.com/1644534/31868429-c9deb254-b796-11e7-8a12-6631fb33900f.jpg)

It only writes to the second half of the screen, with tiny text cut in half.

```
# even though the display has a height of 32, I tried 64 to see
./ssd1306 -h 64
```
Results in:

![img_20171023_020332](https://user-images.githubusercontent.com/1644534/31868430-c9f9ffa0-b796-11e7-89fd-dfa1d8a58ccb.jpg)

The display is working fine with their official python library: https://github.com/adafruit/Adafruit_Python_SSD1306/blob/master/Adafruit_SSD1306/SSD1306.py

The **Adafruit 128x64 OLED Bonnet for Raspberry Pi**  is working fine with periph (https://www.adafruit.com/product/3531): 

![img_20171023_021111](https://user-images.githubusercontent.com/1644534/31868509-a1e57264-b797-11e7-9677-4b47f2647f1f.jpg)

**Comment by maruel** [comment]
Interesting. Can you try changing this line:
https://github.com/google/periph/blob/master/devices/ssd1306/ssd1306.go#L207
to `0xDA, 0x02,` ?

**Comment by mikegleasonjr** [comment]
@maruel nope, same problem.

I don't know if it is relevant/interesting or not but... if I try with `-h 32` on the 128x64 display, it displays on the bottom half of the screen (like 1st screenshot, but on the 128x64 device)

**Comment by mikegleasonjr** [comment]
@maruel I picked up the device again and found the problem this time.

I looked at how the device was initialized with the adafruit python library (https://github.com/adafruit/Adafruit_Python_SSD1306/blob/master/Adafruit_SSD1306/SSD1306.py#L309). I found a mismatch here https://github.com/google/periph/blob/master/devices/ssd1306/ssd1306.go#L207.

So I replaced...

```
0xDA, 0x12, // Set COM pins hardware configuration; see page 40
```

with...

```
0xDA, 0x02, // Set COM pins hardware configuration; see page 40
```

And now the display is working properly:

![img_20171116_212949](https://user-images.githubusercontent.com/1644534/32916902-67e37dd6-cb15-11e7-8571-d5278e219882.jpg)

There is no public interface to send commands directly to the display, what do you propose to make something flexible so I can make it work?

**Comment by mikegleasonjr** [comment]
@maruel I feel silly, that was your proposed diagnosis the first time!

**Comment by mikegleasonjr** [comment]
I found out how to do it:

```
if err = c.Tx(0x3C, []byte{
    0x00, // I²C transaction has stream of command bytes
    0xDA, // set comm pins
    0x02, // 2
}, nil); err != nil {
    return nil, err
}
```

I am going to close it now :)

**Comment by maruel** [comment]
No worries. :) Reopening because this is a bug.

So clearly the COM pins configuration needs to either have more conditions or be made configurable. I think we'll need the later as this really depends on the hardware configuration. :/ Expanding on the doc which isn't that clear;

Bits
- 5 enables top and bottom panel swap
- 4 enables alternative each side instead of using two subpannels

This is coupled with C0/C8:
- C0 means bottom-top
- C8 means top-bottom

It is used to rotate the display.

So we'll need an enum to clarify the above in a way that keeps the rotated functionality working (which I'd prefer if possible).

**Comment by maruel** [comment]
FTR, I still want to fix this, I just need to figure out the best way to expose the bit.

**Comment by maruel** [comment]
I'm starting to think about v3, this should be fixed in time for this release, which will likely be in a few months.

**Comment by mikegleasonjr** [comment]
@maruel thanks! in the meantime I have a workaround so that's great

**Comment by mikegleasonjr** [comment]
Thank you very much!
