### ISSUE TITLE
bcm283x: Do not use dmaWaitcyclesMax.

### ISSUE THREAD

**Issue by simokawa** [google/periph#198]
It looks like `dmaWaitCycles` is a count for bus clock rather than `DREQ` which is our DMA clock. 
- Non-zero waits in `initBlock` for DMA CB does not work as a divisor of the DMA clock and we should remove the argument. 
- `dmaWaitcyclesMax` is not meaningful for upper bound of the divisor. We want to replace it with 0 in most cases.

**Comment by maruel** [comment]
Merged to https://github.com/periph/host/issues/44.
