### ISSUE TITLE
bmxx80: Humidity is 10x smaller than it should be

### ISSUE THREAD

**Issue by zbikmarc** [google/periph#256]
Humidity stored in `physic.Env` is 10x smaller than it should be.

Output shown by example code for bmxx80:
`24.370°C  97.648kPa    5.3%rH`

Example output from Python library for bme280:
`humidity=53.29 % rH`

Example output from c library for bme280
`"humidity":53.01`

**Comment by maruel** [comment]
Which peripheral version are you using?

**Comment by maruel** [comment]
err "periph"

**Comment by zbikmarc** [comment]
that was fast... 
I am using 'master'. Sorry for not mentioning this.

I double checked it with `v3.0.0` tag and result is the same

**Comment by maruel** [comment]
oops I probably messed up on the last refactoring when I increased the resolution 10x and probably missed the calculation.
https://github.com/google/periph/blob/master/devices/bmxx80/bmx280.go#L49
