### ISSUE TITLE
Neopixel LED driver stability

### ISSUE THREAD

**Issue by kaskerd** [google/periph#346]
This is more of a question than a feature request.

The [Neopixel LED driver](https://github.com/google/periph/pull/291/files#diff-2bd32e5fdee2559ed8d3a2d6b29ea462) has been merged into [experimental](https://github.com/google/periph/blob/master/experimental/devices/nrzled/) with a few [examples](https://github.com/google/periph/blob/master/experimental/cmd/nrzled/).

My question is the stability of the driver, and if it will be merged into master, it seem well implemented, but would like to what are the future decisions with the driver.

**Comment by maruel** [comment]
The driver is being rewritten, so do not consider it stable. It is very not stable. When the driver will be promoted to stable this will be announced in the release notes; I generally do not use an issue to track this so I'll close this issue.

Not that it's a bad idea, it's just that I don't have the time to manage the overhead myself.
