### ISSUE TITLE
sysfs-gpio: expose pins found in /sys/class/pwm and reconcile with gpio

### ISSUE THREAD

**Issue by chmorgan** [google/periph#358]
I may intend to submit a pull request to add this support but I'm currently using gobot for pwm support.

**Comment by maruel** [comment]
Can you expand on what you mean exactly?

**Comment by chmorgan** [comment]
It looks like hardware PWM support isn't provided via sysfs:

https://github.com/google/periph/blob/master/host/sysfs/gpio.go#L307

**Comment by maruel** [comment]
Do you ask about using `/sys/class/pwm/` or something else?

**Comment by chmorgan** [comment]
Hi @maruel, yep, isn't /sys/xxx sysfs or am I confused there?

**Comment by maruel** [comment]
What kind of board are you looking for to leverage native PWM on?

**Comment by chmorgan** [comment]
Hi @maruel, in this csae an Omega2+ board. 

I apologize if the support is already present, I combed the codebase, searched etc but I'm still a bit new to sysfs with PWM. I wouldn't want to waste anyones time.

**Comment by maruel** [comment]
I see http://blog.oddbit.com/2017/09/26/some-notes-on-pwm-on-the-raspberry-pi/

I hadn't realize that newer kernels exposed it. That looks totally doable.

**Comment by maruel** [comment]
Independent of Omega or RPi, this is doable, just need someone to add the enumeration and reconciliation with the GPIO pin numbers.

**Comment by chmorgan** [comment]
@maruel yep, I was thinking it would be relatively transparent with respect to the hardware itself. I'm not at the point with periph that I could help contributing anything here yet.

**Comment by maruel** [comment]
Ported to https://github.com/periph/host/issues/40.
