### ISSUE TITLE
physic: Rename ElectricalCapacitance to ElectricCapacitance

### ISSUE THREAD

**Issue by maruel** [google/periph#391]
When you look at https://periph.io/x/periph/conn/physic#pkg-examples, the type ElectricalCapacitance really stands out of the other ElectricFoo types. In hindsight, we should have used the same prefix. Thankfully this type was added fairly recently so while it's disruptive and falls into the v4 bucket, it should not break too many users.

cc @NeuralSpaz

**Comment by NeuralSpaz** [comment]
agreed.

**Comment by maruel** [comment]
Moved to https://github.com/periph/conn/issues/2.
