### ISSUE TITLE
It is not safe to write arbitrary data to the log

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/periph#411]
In line 175, c.Value comes from a cookie, controlled by the user, and writing to the logging system is not secure.
https://github.com/google/periph/blob/d1d1000d375064fa2938b8ab007ae2e23055bdaa/experimental/cmd/periph-web/web.go#L167-L175

**Comment by maruel** [comment]
It doesn't define what is "not secure". Given it's using %q, I'm not too concerned about it.
