### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/periph#412]
Here `n` is always 0, which is assigned in line 301.
https://github.com/google/periph/blob/d1d1000d375064fa2938b8ab007ae2e23055bdaa/experimental/devices/mfrc522/commands/low_level.go#L325-L327

Note that `n` in line 304 is another `n`.

**Comment by maruel** [comment]
This is a real bug  @vkorn authored this code.

**Comment by vkorn** [comment]
Good catch, missed this while porting from the original implementation https://github.com/google/periph/commit/6cccd47c2e387ecc8de14b6aea17efd677bb12b6#diff-12eb6a9015fc0f790550753603f10f98L285

I'm away from laptop today, will address tomorrow.
