### ISSUE TITLE
Feature SSD1322

### ISSUE THREAD

**Issue by MarkoBursic** [google/periph#424]
Is there a plan to support also the display SSD1322 via SPI 3/4-wire, soon?

**Comment by maruel** [comment]
To be clear, I appreciate contributions to extend hardware support. :)

**Comment by MarkoBursic** [comment]
I understand. Can you give a brief info on how you proceeded writing SSD1306, perhaps an example written in different language that you ported in your project. SSD1322 seems to be very close, so many of your code might be reused.

**Comment by maruel** [comment]
I always start from the datasheet, never from another drivers. There's multiple reasons for this.

If you can make the other driver more generic go for it. I seem to recall someone implementing a 4 bits image and driver but I forget if it was merged in or living out of tree; I'm currently in transit so can't confirm.

**Comment by maruel** [comment]
If you want to work on this, please contribute to https://github.com/periph/devices.
