### ISSUE TITLE
Omega2: declare headers

### ISSUE THREAD

**Issue by webdizi** [google/periph#428]
On Omega2 PINs SPI are defined as:
`/dev/spidev0.1
  SPI0.1
  CLK : INVALID  MOSI: INVALID  MISO: INVALID  CS  : INVALID`

How to assign pins yourself?

**Comment by maruel** [comment]
You create a registered header. See the following examples in the code: beagle, chip, odroidc1, rpi.

**Comment by maruel** [comment]
I think declaring the omega2 headers is a fine request so reopening.

**Comment by maruel** [comment]
If you still want it please open an issue at github.com/periph/host. I don't have one personally do I can't work on this.
