### ISSUE TITLE
gpio smoke test needs to open every pin

### ISSUE THREAD

**Issue by tve** [google/periph#81]
The gpio smoke test needs to open every pin (perhaps do an `In(gpio.PullNoChange, gpio.None)`) to ensure that the pins we claim can be used can actually be used, or at least opened. This is particularly important using sysfs.

**Comment by maruel** [comment]
I actually enabled this indirectly, with `headers-list` which displays all pins. It doesn't fails on read error, but these are expected in practice on some systems (!) So I'll close the issue.
