### ISSUE TITLE
gpio smoke test needs to test exceeding the number of edge pins

### ISSUE THREAD

**Issue by tve** [google/periph#83]
Write a test that exceeds the number of gpio pins with edge detection and verify that the error message makes sense.

**Comment by maruel** [comment]
I think https://github.com/google/periph/blob/master/conn/gpio/gpiosmoketest/gpiosmoketest.go#L202 does what you ask for, is it right?

**Comment by maruel** [comment]
I'll close since https://github.com/periph/host/issues/39 will change the dynamics a lot. Let's file an issue at https://github.com/periph/host if we should add this.
